HW06
Otus-DevOps-2017-11/lakostin_infra pull request #2
Opened 2017-12-27 19:05 UTC by lakostin

2017-12-28 09:12 UTC, Nklya commented
Описание PR нужно заполнять.
<img width="789" alt="screen shot 2017-12-28 at 12 12 01" src="https://user-images.githubusercontent.com/26086394/34406127-567ca8b4-ebc8-11e7-8189-06e3b928ed93.png">

2017-12-28 09:18 UTC, Nklya requested changes
Добрый день.

Антон, условия дз выполнены, подготовка и деплой практически корректные.
Замечания:
1. Заполни описание PR
2. Файлы из предыдущего ДЗ нужно было перенести в VPN, а не дублировать
3. Команды для создания инстанса и правил нужно указать в ридми. Если хочешь, скрипты с ними можешь оставить.
4. В deploy.sh у тебя закомментирована команда инстала гемов.

2017-12-28 09:18 UTC, Nklya commented on VPN/Infra_test_bastionvpn.ovpn
> +#{
В директорию VPN нужно было перенести все файлы из предыдущего ДЗ, а не коммитить их снова. У тебя теперь они и в корне и в папке VPN

2017-12-28 09:18 UTC, Nklya commented on VPN/config
> +##########Otus DevOps##########
В директорию VPN нужно было перенести все файлы из предыдущего ДЗ, а не коммитить их снова. У тебя теперь они и в корне и в папке VPN

2017-12-28 09:18 UTC, Nklya commented on VPN/setupvpn.sh
> +#!/bin/bash
В директорию VPN нужно было перенести все файлы из предыдущего ДЗ, а не коммитить их снова. У тебя теперь они и в корне и в папке VPN

2017-12-28 09:18 UTC, Nklya commented on create_fw_rule.sh
> +#!/bin/bash
Это по сути однострочные команды. Лучше их просто указать в ридми заключенными в блок ```

2017-12-28 09:18 UTC, Nklya commented on create_instance.sh
> +#!/bin/bash
Это по сути однострочные команды. Лучше их просто указать в ридми заключенными в блок ```

2017-12-28 09:18 UTC, Nklya commented on create_instance_with_startup.sh
> +#!/bin/bash
Это по сути однострочные команды. Лучше их просто указать в ридми заключенными в блок ```

2017-12-28 09:18 UTC, Nklya commented on delete_fw_rule.sh
> +#!/bin/bash
Это по сути однострочные команды. Лучше их просто указать в ридми заключенными в блок ```

2017-12-28 09:18 UTC, Nklya commented on deploy.sh
> +#cd reddit && bundle install
А зачем закомментировано?

2017-12-28 21:53 UTC, lakostin commented on VPN/Infra_test_bastionvpn.ovpn
> +#{
Каким образом тогда нужно было это сделать?

2017-12-28 21:55 UTC, lakostin commented on deploy.sh
> +#cd reddit && bundle install
Исправил.

2017-12-28 21:55 UTC, lakostin commented on VPN/Infra_test_bastionvpn.ovpn
> +#{
ревёрт коммита теперь нужно сделать?

2017-12-28 22:06 UTC, lakostin commented on delete_fw_rule.sh
> +#!/bin/bash
ок

2017-12-28 22:06 UTC, lakostin commented on deploy.sh
> +#cd reddit && bundle install
исправил.

2017-12-28 22:06 UTC, lakostin commented on create_instance_with_startup.sh
> +#!/bin/bash
ок.

2017-12-28 22:06 UTC, lakostin commented on create_instance.sh
> +#!/bin/bash
ок

2017-12-28 22:06 UTC, lakostin commented on create_fw_rule.sh
> +#!/bin/bash
ок.

2017-12-29 07:16 UTC, Nklya commented on VPN/Infra_test_bastionvpn.ovpn
> +#{
Нужно было создать папку VPN и переместить в нее файлы, относящиеся к предыдущему ДЗ. 
Реверт коммита делать не вижу смысла. Просто удали из корня файлы для VPN и закоммить.

2017-12-29 07:17 UTC, Nklya approved these changes
Добрый день.

Антон, условия дз выполнены, подготовка и деплой корректные.

Удали дублирующие файлы прошлого ДЗ из корня репозитория.

2018-01-08 21:15 UTC, merged