Ansible 3
Otus-DevOps-2017-11/lakostin_infra pull request #8
Opened 2018-02-03 15:15 UTC by lakostin

Выполнено основное ДЗ.

2018-02-05 12:37 UTC, Nklya requested changes
Ревью после мержа предыдущего.

2018-02-10 13:38 UTC, lakostin commented
Предыдущий вмержил.

2018-02-14 18:34 UTC, Nklya approved these changes
Добрый вечер.

Условия дз выполнены, все выглядит относительно ок.

Почему не все старые файлы перенесены из ansible в old?

2018-02-14 18:34 UTC, Nklya commented on terraform/modules/app/main.tf
> +      "9292", "80",
Это лучше делать отдельным ресурсом.

2018-02-14 18:34 UTC, Nklya commented on terraform/stage/variables.tf
> +  default = "reddit-app-base"
А  в чем смысл этого переименования?

2018-02-17 09:52 UTC, lakostin commented on terraform/modules/app/main.tf
> +      "9292", "80",
ок

2018-02-17 09:52 UTC, lakostin commented on terraform/stage/variables.tf
> +  default = "reddit-app-base"
для единообразия

2018-02-17 10:09 UTC, merged